### ISSUE TITLE
Add webm as alternate source for background video

### ISSUE THREAD

**Issue by casassg** [casassg/mcdaga#13]
- Convert MP4 to webM
- Add to repo
- Add to <video> as alternate source
  - `<source src="videos/fireworks.webm" type="video/webm">`

**Comment by casassg** [comment]
It doesn't work on some browser, so adding webm should increase back compatibility

Browser that don't work:
- Firefox at FIB - 47.0

**Comment by AlbertSuarez** [comment]
I'll study it this afternoon!

**Comment by casassg** [comment]
Nop. Reopening and fixing. Needs to be both.

**Comment by AlbertSuarez** [comment]
Fixed!
